package gdc.taxi.datamanager.pojo;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonContacts generated by hbm2java
 */
@Entity
@Table(name = "person_contact", catalog = "gdc_person")
public class PersonContact implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 6274747113539333624L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person", nullable = false)
	private Person person;
	@Column(name = "number", length = 50)
	private String number;
	@Temporal(TemporalType.DATE)
	@Column(name = "sys_add_date", length = 10)
	private Date sysAddDate;
	@Column(name = "status", length = 5)
	private String status;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the person
	 */
	public Person getPerson() {
		return person;
	}

	/**
	 * @param person the person to set
	 */
	public void setPerson(Person person) {
		this.person = person;
	}

	/**
	 * @return the number
	 */
	public String getNumber() {
		return number;
	}

	/**
	 * @param number the number to set
	 */
	public void setNumber(String number) {
		this.number = number;
	}

	/**
	 * @return the sysAddDate
	 */
	public Date getSysAddDate() {
		return sysAddDate;
	}

	/**
	 * @param sysAddDate the sysAddDate to set
	 */
	public void setSysAddDate(Date sysAddDate) {
		this.sysAddDate = sysAddDate;
	}

	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}


}
